Milestone : Add relationships
ahmed025566/oop_school_libarry pull request #3
Opened 2023-08-09 20:44 UTC by ahmed025566

In this milestone you could see that I have done the following:

- I have created classroom class with a method to add students.
- I have created book class to initialize new books with a property rentals in it.
- I have created rentals class to initialize a new rental witch will be stored in rentals in both book and person.

2023-08-09 21:04 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @ahmed025566 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️classes created successfully

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-09 21:04 UTC, tugsem commented on student.rb
>  class Student < Person
- [ ] As a student belongs to a class, please write a method to serve this purpose. Please feel free to check this link for more detail. https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships

2023-08-09 21:04 UTC, tugsem commented on book.rb
> +    @rentals = []
- [ ] Please add a method for adding a rental as Book and Person class has-many-through relationship using the Rental class. The book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship

2023-08-09 21:04 UTC, tugsem commented on person.rb
> +    @rentals = []
- [ ] Please also add here a method to add rentals using the Person class. The person himself should be sent as a parameter to create the new rental achieving the 'has-many' association.

2023-08-10 00:25 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @ahmed025566 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 00:25 UTC, tresorsawasawa commented on student.rb
> +  end
- [ ] Good job trying to fix change(s) mentioned by the previous reviewer. However, as you are supposed to add a method that serves a student belongs to a classroom, kindly ensure that you update it to something similar to this one:
```ruby
  attr_reader :classroom

 def initialize(age, classroom, name = 'Unknown', parent_permission: true)
    super(age, parent_permission: parent_permission, name: name)
    @classroom = classroom
 end
  .
  .
  def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

2023-08-10 00:41 UTC, Munsa1 approved these changes
Hi @ahmed025566, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes By Previous Reviewers :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 14:30 UTC, merged